"""update user model

Revision ID: 354d5b8b5ab3
Revises: 55a25109ac4a
Create Date: 2023-03-10 08:32:42.054694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354d5b8b5ab3'
down_revision = '55a25109ac4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
