"""update user model

Revision ID: 49891697b1b4
Revises: 9e39b6b46b9e
Create Date: 2023-03-09 09:02:44.434153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49891697b1b4'
down_revision = '9e39b6b46b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
