"""update user model1

Revision ID: 719a9a8feb78
Revises: 6e66481acb25
Create Date: 2023-03-10 14:38:37.908371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719a9a8feb78'
down_revision = '6e66481acb25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    # ### end Alembic commands ###
