"""update user model

Revision ID: 783ebc1f5f89
Revises: ff70b5a5ff8e
Create Date: 2023-03-09 09:15:43.810693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783ebc1f5f89'
down_revision = 'ff70b5a5ff8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=False))

    # ### end Alembic commands ###
